"""Command-line interface for the program."""

from argparse import ArgumentParser, Namespace

from core_helpers.cli import setup_parser
from rich import print

from xdg_ninja_report.consts import PACKAGE
from xdg_ninja_report.consts import __version__ as VERSION
from xdg_ninja_report.consts import __desc__ as DESC

parser: ArgumentParser


def get_parsed_args() -> Namespace:
    """
    Parse and return command-line arguments.

    Returns:
        The parsed arguments as an argparse.Namespace object.
    """
    global parser

    parser, g_main = setup_parser(package=PACKAGE, description=DESC, version=VERSION)

    g_main.add_argument(
        "-rf",
        "--report_file",
        default=None,
        metavar="report_file.txt",
        help="File with the xdg-ninja output. Can be generated by `xdg-ninja > report_file.txt`",
    )

    return parser.parse_args()


def parser_error(err_msg: str) -> None:
    """
    Print the error message and the help message and exit.

    Args:
        err_msg (str): The error message to print.

    Returns:
        None
    """
    global parser

    print(f"[red]ERROR[/]: {err_msg}\n")
    parser.print_help()
